### ISSUE TITLE
Input data placed into their own data/ folder in an open format

### ISSUE THREAD

**Issue by mgalland** [ScienceParkStudyGroup/dual-luciferase#4]
If data could be placed into their own `data/` folder in an open format, it would be a great improvement.

To promote openness (not everyone is using Excel), input data could be saved into two `.tsv` (tabulated separated values) or `.csv` (comma separated values). It is also nice to abide by this open format since it is well rendered online on GitHub (see below). 

https://help.github.com/en/github/managing-files-in-a-repository/rendering-csv-and-tsv-data

**Comment by JoachimGoedhart** [comment]
Currently, input data (information on conditions) is taken from a sheet named 'conditions' that I added to the xlsx file. I could not yet get it to work by reading it from a separate CSV and merge it with the that is read from the xlsx datafile. (I added this CSV the repo)

**Comment by JoachimGoedhart** [comment]
This issue is addressed in the branch "Issue 04 conditions from csv" - now allowing the conditions to be read from external CSV
